### ISSUE TITLE
Approach to bar chart, histogram, epicurve

### ISSUE THREAD

**Issue by charlesknightsbridge** [EpiData-dk/analysis#15]
My original take on epicurve was to make it a one-off graph command. It has become obvious that epicurve  is an instance of histogram, which in turn is an instance of a frequency barchart.

So I plan to look at this again and start with barcharts of frequency data. All of these charts should be able to be stratified, so they are one variable commands with or without stratification. This would be unusual for a histogram, I suppose, but not impossible.

The data for stratified barchart is a TwoWayTable created by TABLES. For unstratified charts, we could use FREQ, but that yields an EpiDatafile. So I propose using TABLES to get the data for any barchart, including histogram or epicurve. In the univariate situation, the call to ExecTable requires a second variable, so we can use a dummy variable with constant value 0. This is fairly simple and will avoid having two different ways of getting the chart data (basically counts by the x axis variable).

Does this make sense (TORSTEN)?

The more generic bar chart uses two variables to plot the bars, which is a different thing altogether. We might need a different name for what I'm calling a frequency barchart.

The three commands will have differing variable type requirements (histogram and epicurve require interval data; barchart does not), which are taken care of by the command syntax.

To do the charts, histogram and epicurve will have their own custom data source requirements, which is easily accommodated.

Question for JENS - should I be looking at the group of quality control charts first?

**Comment by torstenchr** [comment]
In my world i would always go with a unique implementation for each graph. We have already seen how things gets very very entangled in Analysis Classic when we try to reuse code between some of the graphs.

The datafiles (or other objects) that comes from tables or freq are always the responsibility of the creator and so it should be. That is why I use the UserDefinedChartSource, so I am able to control when the created data should be destroyed.

I will at any point vote for one chart = one command = one implementation.

Does that answer your question?

**Comment by charlesknightsbridge** [comment]
OK. I see your point, but, in principle, OOP would have me factoring or reusing more than I do when I code.

epicurve and histogram are 99% identical, so I feel I have to have them coming out of the same unit, or one executing the other. For now, I'll just code epicurve. 

After an evening of wrestling with ubuntu, .NET, wine and Gold Builder, I finally have Gold Builder running. In the end, there was a good hint to getting this going on winehq.org. 

However, I officially have a hate on for the author of Gold Parser because he has not maintained it and has not released the code as promised over a decade ago. Plus, it is build on the somewhat obscure .NET 3.5 Framework. Fortunately some wizard had created a winetrick to install this version. M#@%^%Soft doesn't even acknowledge v 3.5 any more. 

I could have been reading a good book, but ... I'll plan to add the epicurve command tomorrow to see if I can successfully build the grammar file and .inc

**Comment by charlesknightsbridge** [comment]
Epicurve is working; can stratify as well by providing a second variable on the command.
Still have to accommodate more than 5 strata.
![epicurve2](https://user-images.githubusercontent.com/855040/180481887-bbcbd802-0ca8-40ee-bf13-d62fbe0443dd.jpg)
![epicurve1](https://user-images.githubusercontent.com/855040/180481891-56d3faa9-135c-45c4-ad92-cbb85215dcf4.jpg)

**Comment by torstenchr** [comment]
> However, I officially have a hate on for the author of Gold Parser because he has not maintained it and has not released the code as promised over a decade ago. Plus, it is build on the somewhat obscure .NET 3.5 Framework. Fortunately some wizard had created a winetrick to install this version. M#@%^%Soft doesn't even acknowledge v 3.5 any more.

I completely agree with that but to change to something else at this point or start writing my own parser would simply be too daunting a task. We would be talking months of full time work in order to do so...

**Comment by charlesknightsbridge** [comment]
The parser itself doesn’t need changing, but it’s close to having all the portability of an MS-DOS software… I DID get it running, though, so no complaints.

I added three commands to the syntax: epicurve, histogram and barchart. No short forms for any of them for now. That isn’t reflected in the commits; only epicurve was added to AST and the graph command launcher.

Jamie

**Comment by charlesknightsbridge** [comment]
I'm trying to provide data to the barchart series using UserDefinedChartSource, but it's working very badly. TAChart makes 410 calls to get data for 14 points! Only the first 14 calls have useful data. For some reason, after that, my procedure returns zeros. I had the unstratified epicurve show up once, but that's gone too after some changes to get stratified bars to show up.

What I like about this approach is that epicurve, histogram and bar chart could use the same user defined chart source. What I don't like, is that it's really difficult to debug and I can't find a working example online of a bar chart with user defined source. Hmmmm, maybe there's a message in that.

**Comment by charlesknightsbridge** [comment]
OK. **Solved this.** Data are now handled in userdefinedchartsource (epicurvesource). This will also work with histograms quite well, so I'll propose that it be called histogramsource in a future branch. A user defined chart source for barchart will be similar, but it will have its own. 

I don't like that the chart source is called multiple times, but I suppose this has to do with laying out the resulting barchart in steps that require the data more than once. I don't like that kind of programming (calling a routine to get a single data item), but it avoids allocating memory, I suppose. I know, I'm old school....

**Comment by charlesknightsbridge** [comment]
Back to basics! 
Epicurve and Histogram will have their own chart data sources, but both will be driven by a common data structure (BINS or something like that). So I'll be undoing much of what is in the jamie/epicurve branch and rebuilding in a better way. At least I know how to get the charts out.

**Comment by charlesknightsbridge** [comment]
Much simpler now. I've implemented epicurve and histogram commands on a common histogramData object, which could be used elsewhere.

Epicurves are implemented by the histogramToEpicurve method of histogramData. This essentially spreads each histogram bar into a series of bars of height 1. Everything else in this unit is common to both chart types.

Both use a common histogramSource chart source, since the actual creation of the plot is identical. Both work with integers and dates. Histogram will allow float data, but counts are accumulated for integer values only. This might be up for discussion.

Both allow you to specify a positive, non-zero interval width to group bars on the x-axis. Somewhat useful, but, in general, the user is responsible for ensuring the x-values make sense, represent whole numbers and allow for increments of 1 (or the interval specified). Histogram supports weighted data. That just doesn't make sense for epicurve.

The code for the two chart commands is pretty straightforward and I've tried to code histogramData and histogramSource in a way that might show Torsten that I'm learning.

We're off for a week, hoping that our phone/TV/internet service is restored before we get back. Using our cell phones as hotspots for the last 10 days has not been ideal. (Our service provider's technician cut our service while dealing with our neighbour. He thought the buried cable to our house was a dead line. I imagine he used some kind of external signal detector. Too bad those don't work on fibre optics!)

**Comment by charlesknightsbridge** [comment]
Dialog is implemented for histogram/epicurve.
There is only one dialog! It seems crazy to do one for each, but this can change if desired.
The dialog has an option  for Epicurve on the variables page, since it is a major option that can affect how other options are used. Opinions?

**Comment by charlesknightsbridge** [comment]
Still working on these. Once I get to barchart, I will rewrite histogramSource as barChartSource, which provides the common source for all three chart types. Still undecided whether they all use a common barChartData object or if histogramData and epicurveData are descendants of barChartData.

**Comment by charlesknightsbridge** [comment]
barchart done, but it has its own barchartsource; 
barchartsource works from FREQ or TABLES output directly, so it is much simpler than histogramcource
