### ISSUE TITLE
FREQ needs to have !w:=var option

### ISSUE THREAD

**Issue by charlesknightsbridge** [EpiData-dk/analysis#16]
FREQ was written without provision for weights. 
I added !w option to epicurve (not sure it will ever be used, but it could be used for histogram); however, this has no effect if only a single variable is specified. With a single variable, EPICURVE calls FREQ; with multiple variables, it calls TABLES.

I think, in general, that we should allow for weights where this makes sense.

The change in FREQ should be straightforward, just a matter of adding the weight variable to the AGGR function list.
I'll give it a try unless there is any objection.

**Comment by charlesknightsbridge** [comment]
After some more thought, EPICURVE should not have !w option, but HISTOGRAM should.
I'll work out a couple of things in EPICURVE and then work on HISTOGRAM

**Comment by charlesknightsbridge** [comment]
Done!

**Comment by torstenchr** [comment]
@charlesknightsbridge I don't think we should close issues before the code has been merged into master.

**Comment by charlesknightsbridge** [comment]
OK. Getting ahead of myself. There are still a couple of behaviours I'm trying to track down; getting the Y-axis intervals consistent is a challenge, but I want to make them automatic, rather than specifying anything e.g. occasionally, even though the Y-values are whole numbers, TAChart occasionally puts in y.5 axis ticks.
It's not a big deal, however.

**Comment by charlesknightsbridge** [comment]
Working through this, I'm of the opinion that FREQ should not have a !w option. FREQ takes a simple view of data and is normally used for data verification, not analysis. The impetus was to allow for weights in histograms and bar charts, but these no longer use FREQ. We can open something like this again (but with a focus on FREQ, not graphs) if there is ever a need.
