### ISSUE TITLE
Help file is too difficult to update

### ISSUE THREAD

**Issue by charlesknightsbridge** [EpiData-dk/analysis#18]
Adding a command is a pain. I've got to find a better HTML editor.

I'd love to be able to use simpler markup and have that ported to HTML. I think that the python help file is managed this way.

**Comment by charlesknightsbridge** [comment]
Here's what I suggest, using markdown, which GIT automatically parses to HTML as here.

# Markdown for EpiData documentation

Style guide
---
The documentation markdown is based on vanilla markdown, although it does have a Table of Contents. The resulting commands.html file must function as a standalone help file as well as integrate with Analysis.

## Syntax used

* Command titles use second level headings: `##`

 This is so that only the command titles will appear in the table of contents
 
* Command titles have an additional html identifier to allow Analysis to open the file at the command description

  ``` 
<a id=command>
## command
  </a>
```

  No other heading may use the markdown heading character `#`. Instead use an html header like `<h3> .... <\h3>`

* There are normally five sections for any command, following the command name
 - Comand syntax in a code block, using ``` or ~~~ on their own line before and after the code
 - Simple command explanation as paragraph text
 - Parameters, listing the allowed variables or expressions. Parameters do not start with `!`. This section begins with a heading:  `<h3>parameters</h3>`. Each parameter should be in-line marked as code with \` before and after.
 - Options, listing all options (that start with `!`). This section begins with an html heading: `<h3>options</h3>`. Each option should be in-line marked as code with \` before and after.
 - Examples, showing some example commands in an indented code block

  	```
  	read "testdata.epx" !force;
  	freq id;
  	```
There is no standard for using *emphasis* or **bold** or ***both***, but try to keep it simple. Notes should begin with `>Note:`, which displays as 
>Note:.

Major documentation sections should be level one headers

```
# Read and Save
```  
displays as

# Read and Save

and also adds a table of contents subhead.

**Comment by charlesknightsbridge** [comment]
First run at this is complete for the commands in trunk (plus some revisions to survival)

**Comment by torstenchr** [comment]
I really love this idea. I too have been annoyed with maintaining the html file.
One question though - how do we generate the .html file from the .md file. This is a requirement during build as we only want to maintain one file - the .md file?

**Comment by charlesknightsbridge** [comment]
Will this do it?

https://github.com/maxhoffmann/yaml-markdown-to-html
