### ISSUE TITLE
no methods for result type rtArray?

### ISSUE THREAD

**Issue by charlesknightsbridge** [EpiData-dk/analysis#25]
rtArray is a legal result type for an option expression, but there seem to be no methods to validate or access such an array.

use case:

set "survival_intervals" := "100,500,1000,5000"; // current use, requiring command to ensure validity of each element

better approach:

set "survival_intervals" := (100,500,1000,5000); // set option of type [rtInteger, rtArray]

Probably need to define array in grammar as well...

**Comment by charlesknightsbridge** [comment]
Agree. I was thinking only of an array for options, but it's not necessary. I need to understand better how actual data is made available internally, since the computations for regression can be done by the LMath package if we can pass a vector or matrix of values.

**Comment by torstenchr** [comment]
Should we close this issue again?
