### ISSUE TITLE
tables fails (sometimes) when stratified data has one variable that is constant

### ISSUE THREAD

**Issue by charlesknightsbridge** [EpiData-dk/analysis#40]
Problem arises with tables with large counts and 1 x n stratified tables
------ Previous dialogue -------
The error does occur with the tables command using the same data as survival. The index out of range error occurs when copying cells from an AggregatedTable object to a TwoWayTable object. In your data, there are 36 rows, so a row index of 35 should be valid at this point. There are some odd, but consistent, behaviours that lead me to suspect that something is corrupting memory:

- If you immediately repeat the command, you get a different error indicating an attempt to access an invalid part of memory

- the error only occurs when there is only one column in the result AND with the variable s, which has fewer numbers in the second of two stratified TwoWayTables. With variable sex, the smaller number is in the first of two tables. If I alter a single record to force two columns, there is no error.

- if I reverse the variables (`tables t runok !by:=s`) there is no error!

Tables with a constant in one of the two variables are common. I create them for barchart, histogram, epicurve and Pareto as they allow me to use weights.

**I have a lot of difficulty debugging the code that causes the error because it is written as an Interface**. The debugger on Mac does not let me inspect objects and variables that belong to a class defined as an interface or any method of that class. Maybe I need to set some debug option to do this, but I haven’t found it yet.

I’ll try to find some code that might not respect Row size of Column size, but it’s a long shot.
*none found so far*

I’ll also set up a loop to see if there is a magic table size where the error starts to occur. 
*error kicks in when the first 1566 records are selected*

**Comment by charlesknightsbridge** [comment]
I can confirm that the error arises in TABLES and not AGGREGATE. If I aggregate the test data, using the recoded variable s, then run tab on the aggregated dataset, I get the same error
```
read "examples/marathon.epx" !force;
new v t i := integer(dectime * 10);
new v s i := (sex = 1);
agg runok t s !ds:=withs;
use withs;
tab runok t !by:=s !w:=n;
*ERROR: Unhandled error during execution: 
  Index out of bounds: 35*
```

**Comment by torstenchr** [comment]
@charlesknightsbridge would you be so kind to attach the file to the issue. I have no file that I can test with. 
See  [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) how to do it.

**Comment by charlesknightsbridge** [comment]
With this data set:
`tab runok t !by:=sex`  runs OK
`tab runok t !by:=s`  fails
[tbug.epx.zip](https://github.com/EpiData-dk/analysis/files/10146697/tbug.epx.zip)

**Comment by torstenchr** [comment]
I can see what is the problem now, but I'm a bit away from knowing how to fix this. The aggregate function does not correctly expand the datafile if data is missing at the end of the dataset. I've attached a simple dataset that demonstrates this.
[agg_fail.epx.zip](https://github.com/EpiData-dk/analysis/files/10231805/agg_fail.epx.zip)

compare the commands:
agg a b c !full


with:
table a b !by := c

**Comment by charlesknightsbridge** [comment]
Much simpler problem definition than I had done. 
I've proposed a fix in branch jamie/agg_fix, We need to loop over all variables as a check for missing data at the end of expanding the datafile.
