### ISSUE TITLE
Editor keystrokes are echoed in the command window of the main form

### ISSUE THREAD

**Issue by charlesknightsbridge** [EpiData-dk/analysis#41]
To reproduce:
start analysis
Window/Editor
start typing - keystrokes appear in editor and command line

Is this Mac only??

Is it my Mac only??

I believe that I built analysis from master commits going back to before the new editor was implemented and they all do this. I used github to create new branches using master history at various times from recently to as far back as early 2020. I think that's the right way to do it.

BUT, this behaviour is new - never saw it back in 2020... I'll see what happens with a linux build.

**Comment by torstenchr** [comment]
@charlesknightsbridge is this still an issue with the latest from master? 

I cannot reproduce this on linux or windows, but I do now have a mac to test on.

**Comment by charlesknightsbridge** [comment]
I cannot reproduce it on my Mac, either. Perhaps an artifact from the previous version of FPC / Lazarus.
