### ISSUE TITLE
Display of dates on chart axes

### ISSUE THREAD

**Issue by charlesknightsbridge** [EpiData-dk/analysis#51]
The current approach to dates on a chart axis is to display them using the local system default date format. In a Pareto chart, the dates are displayed using the variable's date format. All charts should display dates this way, that is, using the variable's Field Type (ftDMYDate, etc).

**Comment by torstenchr** [comment]
I do not agree in this case. Unlike data entry where the entry format has to match something specific (ie. could originate from a questionaire), the output format of analysis should fit user settings.

**Comment by charlesknightsbridge** [comment]
Yes. That makes sense. So I’ll fix Pareto to display dates to the user setting.JamieOn Feb 4, 2023, at 4:04 AM, Torsten Bonde Christiansen ***@***.***> wrote:﻿
I do not agree in this case. Unlike data entry where the entry format has to match something specific (ie. could originate from a questionaire), the output format of analysis should fit user settings.

**Comment by charlesknightsbridge** [comment]
Pareto now displays dates (x-axis) per local user settings (same as other graphs)
