### ISSUE TITLE
Save multiple charts from a single command (pareto)

### ISSUE THREAD

**Issue by charlesknightsbridge** [EpiData-dk/analysis#56]
I can get files saved from the command line (branch jamie/saveMultipleCharts)
e.g. pareto x !by:=y !e:="chart.jpg"
will save chart.1.jpg and chart.2.jpg
However, I'm not sure that the charts are freed in my test branch.
Also, I have not yet worked out how to get the graph pop up menu to save just the visible chart; the current implementation always saves the "top" chart, whether it is visible or not.

**Comment by torstenchr** [comment]
@charlesknightsbridge , has the above issue been fixed? I can see you closed the associated PR but haven't closed this issue?

**Comment by torstenchr** [comment]
@charlesknightsbridge  it seems like you have linket multiple PR that does the same thing?? 

I have reviewed the Pareto PR which seems to contain all the other PRs.

**Comment by charlesknightsbridge** [comment]
The Pareto PR did this, but not in the same way. I will have to solve issue with save file names in a simpler way, which will eliminate some of the changes.JamieOn May 22, 2024, at 1:18 PM, Torsten Bonde Christiansen ***@***.***> wrote:﻿
@charlesknightsbridge  it seems like you have linket multiple PR that does the same thing??
I have reviewed the Pareto PR which seems to contain all the other PRs.
