### ISSUE TITLE
Add options for defining min/max value for both axis

### ISSUE THREAD

**Issue by torstenchr** [EpiData-dk/analysis#6]
In graph commands the data area is always bounded by the largest and smallest value on both axis. 

A user should be able to adjust this area with options with explicit values for minimum and/or maximum for both bottom axis and left axes.

**Comment by charlesknightsbridge** [comment]
The options should override any chart-specific values (e.g. Survival sets y-axis bounds to [0,1] by default, but the user can still specify. The problem will be what to do if nonsense bounds are given, such as bounds that exclude all data. Is there a use case for having data outside the axis bounds? I don't think so, but we'll need to think about it. I would propose that a min or max bound is ignored if it would exclude data, with a warning message to the user.

The increment value specified would always be followed.

What syntax?
a) !xmin := low !xmax := high !xinc := increment
b) !xlimits := (low, high [, increment])

**Comment by charlesknightsbridge** [comment]
I prefer option a) above.
(Reminder to me): To force an increment, the simplest method is to create a ListChartSource with all of the desired values and attach it to the axis.

**Comment by charlesknightsbridge** [comment]
Question: what was the intent of the options !sizex and !sizey (I've lost this)?
Was it to set the size of the form containing the chart?
Or was it to set the axis length?
