### ISSUE TITLE
erase command succeeds if file does not exist

### ISSUE THREAD

**Issue by charlesknightsbridge** [EpiData-dk/analysis#96]
erase could be used in validating that chart command output exists (not with the new validate tool).
e.g.
.scatter x y !e:="test.jpg";
.assert (erase "test.jpg");

However, erase always return success.

**Comment by torstenchr** [comment]
This is not a bug, it is such by design!

It was changed on request by @JLepidata  to NOT fail scripts if the file did not exist.

This should be consistent with Analysis Classic behaviour (from what i remember).

**Comment by charlesknightsbridge** [comment]
OK. I don’t know the history. Is the result of use outside of runtest?JamieOn Jul 1, 2024, at 12:41 PM, Torsten Bonde Christiansen ***@***.***> wrote:﻿
This is not a bug, it is such by design!
It was changed on request by @JLepidata  to NOT fail scripts if the file did not exist.
This should be consistent with Analysis Classic behaviour (from what i remember).

**Comment by torstenchr** [comment]
I am rather sure the original request was from Jens @JLepidata to the behaviour. I assume it was for convenience when running scripts at the hospital.

**Comment by charlesknightsbridge** [comment]
I don't see how having erase fail would impact anything. It doesn't stop a .pgm from executing. 
Does the succeed/failed have any effect other than with assert?

**Comment by torstenchr** [comment]
If you change the result value to csrFailed the execution is automatically haled if you are executing multiple lines from within the editor. I think that was the original reason why Jens wanted it changed.

**Comment by charlesknightsbridge** [comment]
OK. My motivation is also for a special case so we can close the issue. JamieOn Jul 2, 2024, at 2:00 PM, Torsten Bonde Christiansen ***@***.***> wrote:﻿
If you change the result value to csrFailed the execution is automatically haled if you are executing multiple lines from within the editor. I think that was the original reason why Jens wanted it changed.
